### ISSUE TITLE
LICENSE info is missing completely

### ISSUE THREAD

**Issue by priv-kweihmann** [mcandre/mage-extras#21]
Unfortunately latest release of `github.com/mcandre/stank` pulls in this repo, but I can't find any info under what license this repository is usable.
So I have to assume it's closed source, so I can't use the latest `stank` release :-(

Please provide some license info in the repo and in the releases (if any)

**Comment by mcandre** [comment]
Apologies. I tend to license all of my projects with the boring, libris *BSD 2-clause* license.

I have now added this formally to the mage-extras repository.
